defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.7
      environment:
        PIPENV_VENV_IN_PROJECT: true

install_packages: &install_packages
  run:
    name: Install developer packages
    command: |
      sudo pip install pipenv
      pipenv install -d
      pipenv run python setup.py clean

restore_cache: &restore_cache
  restore_cache:
    name: "Restore cache"
    key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

version: 2
jobs:
  test-lib:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_packages
      - run:
          name: Run tests
          command: |
            mkdir test-results
            pipenv run pytest --junitxml=./test-results/summary.xml | tee ./test-results/pytest.txt
      - run:
          name: Run rstcheck
          command: |
            pipenv run rstcheck README.rst| tee ./test-results/rstcheck.txt

      - store_artifacts:
          path: test-results
          destination: artifacts
      - store_test_results:
          path: test-results

  publish:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_packages
      - run:
          name: Build a package
          command: |
            bash ./bin/build
      - run:
          name: Publish the package
          command: |
            bash ./bin/publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test-lib
      - publish:
          requires:
            - test-lib
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              only: master
