defaults: &defaults
  working_directory: /srv
  docker:
    - image: circleci/python:3.7

install_packages: &install_packages
  run:
    name: Install developer packages
    command: |
      sudo pip install pipenv
      sudo pipenv install -d --system

restore_cache: &restore_cache
  restore_cache:
    name: "Restore cache"
    key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  test-lib:
    <<: *defaults
    steps:
      - run:
          name: Init
          command: sudo chown circleci:circleci /srv
      - checkout
      - *restore_cache
      - *install_packages
      - run:
          name: Run tests
          command: ./bin/ci/test
      - run:
          name: Run flake8
          command: ./bin/ci/flake8
      - run:
          name: Run mypy
          command: ./bin/ci/mypy
      - run:
          name: Run rstcheck
          command: ./bin/ci/rstcheck
      - store_artifacts:
          path: test-results
          destination: artifacts
      - store_test_results:
          path: test-results
      - codecov/upload

  publish:
    <<: *defaults
    steps:
      - run:
          name: Init
          command: sudo chown circleci:circleci /srv
      - checkout
      - *restore_cache
      - *install_packages
      - run:
          name: Build a package
          command: |
            bash ./bin/ci/build
      - run:
          name: Publish the package
          command: |
            bash ./bin/ci/publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test-lib:
          filters:
            tags:
                only: /.*/
      - publish:
          requires:
            - test-lib
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
